# Generated by Django 3.0.2 on 2020-03-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaPerdida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Barrio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Estado')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Raza')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.Tipo')),
            ],
        ),
    ]
