# Generated by Django 3.0.2 on 2020-03-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0003_mascotaperdida_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='situacion',
            field=models.CharField(choices=[('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado')], default='PERDIDO', max_length=40),
        ),
    ]
