# Generated by Django 3.0.2 on 2020-03-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0004_auto_20200306_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='situacion',
            field=models.CharField(max_length=40),
        ),
    ]
