# Generated by Django 3.0.4 on 2020-03-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0006_auto_20200306_2215'),
        ('Mascotas', '0004_auto_20200306_1904'),
    ]

    operations = [
    ]
